#pragma once

#ifndef DEFS_INC_
#define DEFS_INC_

#define LED_MATRIX_WIDTH  9
#define LED_MATRIX_HEIGHT 360
#define LED_MATRIX_BOXES 10
#define LED_MATRIX_HEIGHT_PER_BOX 36
#define LED_MATRIX_N_LEDS (LED_MATRIX_WIDTH*LED_MATRIX_HEIGHT)

#endif
